### ISSUE TITLE
Make logout from the whole of Ozwillo optional

### ISSUE THREAD

**Issue by schambon** [ozwillo/ozwillo-java-spring-integration#19]
Currently the logout process is:

1 - log out from the application
2 - revoke the token
3 - redirect to the general Ozwillo logout procedure

Step 3 can be problematic in terms of user experience: just because they log out from some application that uses Ozwillo as identity provider, they don't want to be logged out of all their other applications (including the Portal)

Add a configuration option to make general logout optional; if not, provide a post-application-logout URL to redirect to (e.g. a confirmation page saying "you have been logged out, you may close this page" or something similar, it's up to the application)

**Comment by tbroyer** [comment]
Step three will display "you have been logged out of <the application>" (and propose, but not mandate, logging out of all applications, which are listed on the page). If the user doesn't log out of Ozwillo as a whole, he'll be automatically logged back in when returning to the application, which is why the logout page suggests logging out of Ozwillo.
If an application provides a `post_logout_redirect_uri`, then it should (in terms of UX) not be something like "you've been logged out". `post_logout_redirect_uri` is for cases where the user can be redirected to the homepage of the application, or some other page, where he's not forced to log in (i.e. applications/pages where it's OK to be anonymous); any other use IMO would provide a bad UX.

Just sayin'

**Comment by schambon** [comment]
You're right (although I wasn't talking about `post_logout_redirect_uri`, obviously).

Anyway UX-wise that logout page is pretty sub-optimal (it should boldly say "you have logged out of your app" and separately add "do you want to also log out from the other Ozwillo services?", rather than the current inverted emphasis; plus the "Cancel and log me back in" seems to only appear when there is a `post_logout_redirect_uri`, which seems… counterintuitive) but here isn't the place to discuss it.

There are still some issues associated with the logout process - for some reason revoking the token yields a 401 (which causes the logout page to say "You have signed out from XX / You are also signed on to XX"), it might be an issue on our side so I'm keeping this issue open to keep track of it.

**Comment by schambon** [comment]
Closing - the logout issues were on the application side
